### ISSUE TITLE
module 'enum' has no attribute 'IntFlag'

### ISSUE THREAD

**Issue by eliemichel** [pgrit/SimpleImageIO#2]
Trying `pip install simpleimageio` on Windows 10 with Python 3.7.6 fails:

```
$ python --version
Python 3.7.6

$ python -m pip install simpleimageio
Collecting simpleimageio
  Using cached SimpleImageIO-0.6.0.tar.gz (202 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\python37\python.exe' 'c:\python37\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\Elie\AppData\Local\Temp\pip-build-env-odb10xmu\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=42' wheel 'cmake>=3.14'
       cwd: None
  Complete output (14 lines):
  Traceback (most recent call last):
    File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "c:\python37\lib\runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "c:\python37\lib\site-packages\pip\__main__.py", line 23, in <module>
      from pip._internal.cli.main import main as _main  # isort:skip # noqa
    File "c:\python37\lib\site-packages\pip\_internal\cli\main.py", line 5, in <module>
      import locale
    File "c:\python37\lib\locale.py", line 16, in <module>
      import re
    File "c:\python37\lib\re.py", line 143, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python37\python.exe' 'c:\python37\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\Elie\AppData\Local\Temp\pip-build-env-odb10xmu\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=42' wheel 'cmake>=3.14' Check the logs for full command output.
```

I do not seem to have a conflicting installation of `enum`:

```
$ python
Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import enum
>>> enum.IntFlag
<enum 'IntFlag'>
```

**Comment by pgrit** [comment]
This is most likely a conflict with another package or an issue with your Python version. You could try to create a virtual environment and see if the problem persists. https://docs.python.org/3/tutorial/venv.html

Since the crash happens during installation of build dependencies (i.e. CMake), this is almost certainly not a problem with `simpleimageio`, but a problem with `setuptools`.

You can also try a manual local build. If you have CMake installed and in path and a C++ compiler (e.g., Visual Studio with the correct packages for native development) then you should be able to run:

```
python -m pip install --user wheel
python setup.py install
```

**Comment by eliemichel** [comment]
ALl right, I was in a virtualenv and it must have been something in there that was conflicting since I can no longer reproduce it neither in the system wise installation nor in a fresh venv!
